when:
  - event: deployment

matrix:
  DATABASE:
    - not parquetdb and not sqlite
    - sqlite
    - parquetdb
    - prerelease-parquetdb
  EXECUTION:
    - thread_workers
    - process_workers
    - not thread_workers and not process_workers and not interpreter_workers
  MANAGER:
    - not process_manager and not thread_manager and not interpreter_manager
    - thread_manager
    - process_manager

steps:
  - name: headless
    image: zacharyspector/elide:latest
    pull: true
    commands:
      - TMPDIR=$(python find_ramdisk.py)
      - echo "TMPDIR=$TMPDIR"
      - export TMPDIR
      - if [ "${DATABASE}" = 'prerelease-parquetdb' ]; then
      - DATABASE=parquetdb
      - export DATABASE
      - TOXFILE=lisien/tox_prerelease_parquetdb.ini
      - else
      - DATABASE="${DATABASE}"
      - export DATABASE
      - TOXFILE=lisien/tox.ini
      - fi
      - python -m pip install --root-user-action ignore pytest tox lisien/
      - PYTEST_KEYWORDS="not slow and not big and $DATABASE and ${EXECUTION} and ${MANAGER}"
      - echo "will run $PYTEST_KEYWORDS"
      - tox run-parallel -c $TOXFILE
  - name: slow_headless
    image: zacharyspector/elide:latest
    commands:
      - TMPDIR=$(python find_ramdisk.py)
      - echo "TMPDIR=$TMPDIR"
      - export TMPDIR
      - python -m venv .venv${PYTHON_VERSION}
      - . .venv${PYTHON_VERSION}/bin/activate
      - if [ "${DATABASE}" = 'prerelease-parquetdb' ]; then
      - DATABASE=parquetdb
      - export DATABASE
      - TOXFILE=lisien/tox_prerelease_parquetdb
      - else
      - DATABASE="${DATABASE}"
      - export DATABASE
      - TOXFILE=lisien/tox.ini
      - fi
      - PYTEST_KEYWORDS="(slow or big) and $DATABASE and ${EXECUTION} and ${MANAGER}"
      - echo "will run $PYTEST_KEYWORDS"
      - tox run-parallel -c $TOXFILE